# docker-compose.yml (na raiz do projeto)
version: '3.8'

services:
  # Frontend - Cliente React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:3030/api
      - VITE_SERVER_URL=http://backend:3030
    depends_on:
      - backend
    restart: always

  # Backend - API Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
      - MONGO_URI=mongodb+srv://your_mongodb_uri
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=production
      - FRONTEND_URL=http://frontend
    volumes:
      - backend_uploads:/app/uploads
    restart: always

volumes:
  backend_uploads: