# backend/Dockerfile
FROM node:18-alpine

WORKDIR /app

# Instala as dependências
COPY package.json package-lock.json ./
RUN npm ci

# Copia os arquivos do projeto
COPY . .

# Cria o diretório de uploads (caso não exista)
RUN mkdir -p uploads

# Expõe a porta do servidor
EXPOSE 3030

# Comando para iniciar o servidor
CMD ["npm", "start"]